inertial_frame_id: world
waypoints:
  -
    point: [0,  0, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False 
  -
    point: [-100, 10, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-100, 40, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [100, 40, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [100, 70, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-100, 70, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-100, 100, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [100, 100, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [100, 130, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-100, 130, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-100, 160, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [100, 160, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  