inertial_frame_id: world
waypoints:
  -
    point: [0,  0, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-250,  0, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-250,  100, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [250,  100, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [250,  200, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-250,  200, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-250,  300, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [250,  300, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [250,  400, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-250,  400, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-250,  500, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [250,  500, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  # -
  #   point: [250,  600, -45]
  #   max_forward_speed: 1.5
  #   heading: 0
  #   use_fixed_heading: False
  # -
  #   point: [-250,  600, -45]
  #   max_forward_speed: 1.5
  #   heading: 0
  #   use_fixed_heading: False
  # -
  #   point: [-250,  700, -45]
  #   max_forward_speed: 1.5
  #   heading: 0
  #   use_fixed_heading: False
  # -
  #   point: [250,  700, -45]
  #   max_forward_speed: 1.5
  #   heading: 0
  #   use_fixed_heading: False
  # -
  #   point: [250,  800, -45]
  #   max_forward_speed: 1.5
  #   heading: 0
  #   use_fixed_heading: False
  # -
  #   point: [-250,  800, -45]
  #   max_forward_speed: 1.5
  #   heading: 0
  #   use_fixed_heading: False
  # -
  #   point: [-250,  900, -45]
  #   max_forward_speed: 1.5
  #   heading: 0
  #   use_fixed_heading: False
  # -
  #   point: [250,  900, -45]
  #   max_forward_speed: 1.5
  #   heading: 0
  #   use_fixed_heading: False
  # -
  #   point: [250,  1000, -45]
  #   max_forward_speed: 1.5
  #   heading: 0
  #   use_fixed_heading: False
  # -
  #   point: [-250,  1000, -45]
  #   max_forward_speed: 1.5
  #   heading: 0
  #   use_fixed_heading: False
  