inertial_frame_id: world
waypoints:
  -
    point: [0,  0, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [50, 10, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [50, 50, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-50, 50, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-50, 100, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [50, 100, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [50, 150, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-50, 150, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  