inertial_frame_id: world
waypoints:
  -
    point: [0,  0, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-25, 10, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-25, 20, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 20, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 30, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-25, 30, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  