inertial_frame_id: world
waypoints:
  -
    point: [0, 0, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 30, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 60, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 90, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 120, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
