inertial_frame_id: world
waypoints:
  -
    point: [0, 25, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 50, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 75, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 100, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 125, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 150, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 175, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 200, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 225, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 250, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 275, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 300, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 325, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 350, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 375, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 400, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 425, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 450, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 475, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 500, -45]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  