class Keys:
    array_type_name = "array"
    assembly_key_name = "assembly"
    asset_type_name = "asset"
    boolean_type_name = "boolean"
    attributes_key_name = "attributes"
    container_key_name = "container"
    content_key_name = "content"
    context_key_name = "context"
    current_choice_key_name = "current_choice"
    dict_type_name = "dictionary"
    float_type_name = "float"
    hash_key_name = "hash"
    inputs_key_name = "inputs"
    input_set_name = "Data"
    integer_type_name = "integer"
    launchfile_key_name = "launchfile"
    lecinfo_key_name = "lecinfo"
    name_key_name = "name"
    node_named_path_key_name = "node_named_path"
    node_path_key_name = "node_path"
    outputs_key_name = "outputs"
    owner_key_name = "owner"
    parameter_map_key_name = "parameter_map"
    parameters_key_name = "parameters"
    project_name_key_name = "project_name"
    slurm_port_key_name = "slurm_port"
    temp_dir_key_name = "temp_dir"


class Attributes:
    asset_attribute_name = "asset"
    constraint_attribute_name = "constraint"
    choice_list_attribute_name = "ChoiceList"
    current_choice_attribute_name = "CurrentChoice"
    default_value_attribute_name = "defaultValue"
    label_attribute_name = "Label"
    max_attribute_name = "max"
    min_attribute_name = "min"
    name_attribute_name = "name"
    required_attribute_name = "required"
    value_attribute_name = "value"
    datainfo_attribute_name = "datainfo"
    type_attribute_name = "type"
    definition_attribute_name = "definition"
    filename_attribute_name = "filename"
    params_definition_attribute_name = "Definition"
    deployment_key_attribute_name = "DeploymentKey"
    implementation_attribute_name = "IsImplementation"
    isactive_attribute_name = "IsActive"


class References:
    lec_reference_name = 'ModelDataLink'
