/**
 * generated by Xtext 2.25.0
 */
package edu.vanderbilt.isis.alc.btree.bTree;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BB Var</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.vanderbilt.isis.alc.btree.bTree.BBVar#getType <em>Type</em>}</li>
 *   <li>{@link edu.vanderbilt.isis.alc.btree.bTree.BBVar#getName <em>Name</em>}</li>
 *   <li>{@link edu.vanderbilt.isis.alc.btree.bTree.BBVar#getDefault <em>Default</em>}</li>
 *   <li>{@link edu.vanderbilt.isis.alc.btree.bTree.BBVar#getBbvar <em>Bbvar</em>}</li>
 * </ul>
 *
 * @see edu.vanderbilt.isis.alc.btree.bTree.BTreePackage#getBBVar()
 * @model
 * @generated
 */
public interface BBVar extends CheckNode
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Type)
   * @see edu.vanderbilt.isis.alc.btree.bTree.BTreePackage#getBBVar_Type()
   * @model
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link edu.vanderbilt.isis.alc.btree.bTree.BBVar#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.vanderbilt.isis.alc.btree.bTree.BTreePackage#getBBVar_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link edu.vanderbilt.isis.alc.btree.bTree.BBVar#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default</em>' attribute.
   * @see #setDefault(String)
   * @see edu.vanderbilt.isis.alc.btree.bTree.BTreePackage#getBBVar_Default()
   * @model
   * @generated
   */
  String getDefault();

  /**
   * Sets the value of the '{@link edu.vanderbilt.isis.alc.btree.bTree.BBVar#getDefault <em>Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default</em>' attribute.
   * @see #getDefault()
   * @generated
   */
  void setDefault(String value);

  /**
   * Returns the value of the '<em><b>Bbvar</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bbvar</em>' reference.
   * @see #setBbvar(BBVar)
   * @see edu.vanderbilt.isis.alc.btree.bTree.BTreePackage#getBBVar_Bbvar()
   * @model
   * @generated
   */
  BBVar getBbvar();

  /**
   * Sets the value of the '{@link edu.vanderbilt.isis.alc.btree.bTree.BBVar#getBbvar <em>Bbvar</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bbvar</em>' reference.
   * @see #getBbvar()
   * @generated
   */
  void setBbvar(BBVar value);

} // BBVar
