/**
 * generated by Xtext 2.25.0
 */
package edu.vanderbilt.isis.alc.btree.bTree;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see edu.vanderbilt.isis.alc.btree.bTree.BTreePackage
 * @generated
 */
public interface BTreeFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BTreeFactory eINSTANCE = edu.vanderbilt.isis.alc.btree.bTree.impl.BTreeFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Behavior Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Behavior Model</em>'.
   * @generated
   */
  BehaviorModel createBehaviorModel();

  /**
   * Returns a new object of class '<em>Simple Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Type</em>'.
   * @generated
   */
  SimpleType createSimpleType();

  /**
   * Returns a new object of class '<em>Message Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message Type</em>'.
   * @generated
   */
  MessageType createMessageType();

  /**
   * Returns a new object of class '<em>Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type</em>'.
   * @generated
   */
  Type createType();

  /**
   * Returns a new object of class '<em>Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Field</em>'.
   * @generated
   */
  Field createField();

  /**
   * Returns a new object of class '<em>Topic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Topic</em>'.
   * @generated
   */
  Topic createTopic();

  /**
   * Returns a new object of class '<em>BB Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BB Var</em>'.
   * @generated
   */
  BBVar createBBVar();

  /**
   * Returns a new object of class '<em>BB Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BB Event</em>'.
   * @generated
   */
  BBEvent createBBEvent();

  /**
   * Returns a new object of class '<em>Arg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arg</em>'.
   * @generated
   */
  Arg createArg();

  /**
   * Returns a new object of class '<em>Default Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Default Type</em>'.
   * @generated
   */
  DefaultType createDefaultType();

  /**
   * Returns a new object of class '<em>Base Array Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Base Array Type</em>'.
   * @generated
   */
  BaseArrayType createBaseArrayType();

  /**
   * Returns a new object of class '<em>BB Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BB Node</em>'.
   * @generated
   */
  BBNode createBBNode();

  /**
   * Returns a new object of class '<em>Check Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Check Node</em>'.
   * @generated
   */
  CheckNode createCheckNode();

  /**
   * Returns a new object of class '<em>Behavior Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Behavior Node</em>'.
   * @generated
   */
  BehaviorNode createBehaviorNode();

  /**
   * Returns a new object of class '<em>Std Behavior Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Std Behavior Node</em>'.
   * @generated
   */
  StdBehaviorNode createStdBehaviorNode();

  /**
   * Returns a new object of class '<em>Task Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task Node</em>'.
   * @generated
   */
  TaskNode createTaskNode();

  /**
   * Returns a new object of class '<em>Topic Arg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Topic Arg</em>'.
   * @generated
   */
  TopicArg createTopicArg();

  /**
   * Returns a new object of class '<em>BTree</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BTree</em>'.
   * @generated
   */
  BTree createBTree();

  /**
   * Returns a new object of class '<em>Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Node</em>'.
   * @generated
   */
  BTreeNode createBTreeNode();

  /**
   * Returns a new object of class '<em>Child Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Child Node</em>'.
   * @generated
   */
  ChildNode createChildNode();

  /**
   * Returns a new object of class '<em>Par BT Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Par BT Node</em>'.
   * @generated
   */
  ParBTNode createParBTNode();

  /**
   * Returns a new object of class '<em>Seq BT Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Seq BT Node</em>'.
   * @generated
   */
  SeqBTNode createSeqBTNode();

  /**
   * Returns a new object of class '<em>Sel BT Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sel BT Node</em>'.
   * @generated
   */
  SelBTNode createSelBTNode();

  /**
   * Returns a new object of class '<em>SIFBT Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SIFBT Node</em>'.
   * @generated
   */
  SIFBTNode createSIFBTNode();

  /**
   * Returns a new object of class '<em>Mon BT Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mon BT Node</em>'.
   * @generated
   */
  MonBTNode createMonBTNode();

  /**
   * Returns a new object of class '<em>Task BT Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task BT Node</em>'.
   * @generated
   */
  TaskBTNode createTaskBTNode();

  /**
   * Returns a new object of class '<em>Timer BT Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Timer BT Node</em>'.
   * @generated
   */
  TimerBTNode createTimerBTNode();

  /**
   * Returns a new object of class '<em>Check BT Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Check BT Node</em>'.
   * @generated
   */
  CheckBTNode createCheckBTNode();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  BTreePackage getBTreePackage();

} //BTreeFactory
