/**
 * generated by Xtext 2.25.0
 */
package edu.vanderbilt.isis.alc.btree.bTree;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Check Node</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.vanderbilt.isis.alc.btree.bTree.BTreePackage#getCheckNode()
 * @model
 * @generated
 */
public interface CheckNode extends EObject
{
} // CheckNode
