/**
 * generated by Xtext 2.25.0
 */
package edu.vanderbilt.isis.alc.btree.bTree;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.vanderbilt.isis.alc.btree.bTree.TaskNode#getInput_topics <em>Input topics</em>}</li>
 *   <li>{@link edu.vanderbilt.isis.alc.btree.bTree.TaskNode#getOutput_topics <em>Output topics</em>}</li>
 *   <li>{@link edu.vanderbilt.isis.alc.btree.bTree.TaskNode#getBb_vars <em>Bb vars</em>}</li>
 *   <li>{@link edu.vanderbilt.isis.alc.btree.bTree.TaskNode#getArgs <em>Args</em>}</li>
 *   <li>{@link edu.vanderbilt.isis.alc.btree.bTree.TaskNode#getComment <em>Comment</em>}</li>
 * </ul>
 *
 * @see edu.vanderbilt.isis.alc.btree.bTree.BTreePackage#getTaskNode()
 * @model
 * @generated
 */
public interface TaskNode extends BehaviorNode
{
  /**
   * Returns the value of the '<em><b>Input topics</b></em>' containment reference list.
   * The list contents are of type {@link edu.vanderbilt.isis.alc.btree.bTree.TopicArg}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input topics</em>' containment reference list.
   * @see edu.vanderbilt.isis.alc.btree.bTree.BTreePackage#getTaskNode_Input_topics()
   * @model containment="true"
   * @generated
   */
  EList<TopicArg> getInput_topics();

  /**
   * Returns the value of the '<em><b>Output topics</b></em>' containment reference list.
   * The list contents are of type {@link edu.vanderbilt.isis.alc.btree.bTree.TopicArg}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output topics</em>' containment reference list.
   * @see edu.vanderbilt.isis.alc.btree.bTree.BTreePackage#getTaskNode_Output_topics()
   * @model containment="true"
   * @generated
   */
  EList<TopicArg> getOutput_topics();

  /**
   * Returns the value of the '<em><b>Bb vars</b></em>' containment reference list.
   * The list contents are of type {@link edu.vanderbilt.isis.alc.btree.bTree.BBVar}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bb vars</em>' containment reference list.
   * @see edu.vanderbilt.isis.alc.btree.bTree.BTreePackage#getTaskNode_Bb_vars()
   * @model containment="true"
   * @generated
   */
  EList<BBVar> getBb_vars();

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link edu.vanderbilt.isis.alc.btree.bTree.Arg}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see edu.vanderbilt.isis.alc.btree.bTree.BTreePackage#getTaskNode_Args()
   * @model containment="true"
   * @generated
   */
  EList<Arg> getArgs();

  /**
   * Returns the value of the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comment</em>' attribute.
   * @see #setComment(String)
   * @see edu.vanderbilt.isis.alc.btree.bTree.BTreePackage#getTaskNode_Comment()
   * @model
   * @generated
   */
  String getComment();

  /**
   * Sets the value of the '{@link edu.vanderbilt.isis.alc.btree.bTree.TaskNode#getComment <em>Comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comment</em>' attribute.
   * @see #getComment()
   * @generated
   */
  void setComment(String value);

} // TaskNode
