[sys,fit] = QuatSysID(6,'prediction','on','Quat_Experiments/data_sys_id1.csv',...
    'Quat_Experiments/data_sys_id2.csv','Quat_Experiments/data_sys_id3.csv',...
    'Quat_Experiments/data_sys_id5.csv','Quat_Experiments/data_sys_id6.csv')%,...
    %'Quat_Experiments/data_sys_id7.csv','Quat_Experiments/data_sys_id8.csv','Quat_Experiments/data_sys_id9.csv');

cont_sys = d2c(sys,'tustin');
A = regexprep(mat2str(cont_sys.A), {'\[', '\]', '\s+'}, {'', '', ','});
B = regexprep(mat2str(cont_sys.B), {'\[', '\]', '\s+'}, {'', '', ','});