data_dir_name = "data"
exceptions_file_name = "exceptions"
failing_task_path_file_name = "failing_task_path"
generator_name = "gen_program.py"
generator_io_dir_name = "generator_io"
generator_stdout_file_name = "generator.stdout"
generator_stderr_file_name = "generator.stderr"
generator_exceptions_file_name = "generator.exceptions"
init_file_name = "__init__.py"
job_data_dir_name = "job_data"
modules_dir_name = "Modules"
script_dir_name = "script"
script_file_name = "script.py"
script_stderr_file_name = "stderr"
script_stdout_file_name = "stdout"
workflow_data_tree_file_name = "workflow_data_tree.json"

